.\" Manpage for ambunpack.
.\" Contact moose@ylsoftware.com to correct errors or typos.
.TH man 1 "04 Feb 2023" "1.0" "ambunpack man page"
.SH NAME
ambunpack \- unpack AMB-file 
.SH SYNOPSIS
ambunpack -i filename [-o outputdir]
.SH DESCRIPTION
ambunpack is simple tool for unpack amb-files as archives.
.SH OPTIONS
.TP
.B "-i"
Input file. Must be specified.
.TP
.B "-o"
Output directory. Optional. If not specified will be used current directory.
.SH SEE ALSO
amb2html(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Vadim Kalinnikov (moose@ylsoftware.com)